"""Email Lifecycle Notifications — applicant communication.

Production lenders send a sequence of emails throughout the loan journey:
  1. Application Received — immediate acknowledgment
  2. Decision — approval or denial (generated by Claude)
  3. Marketing alternative — sent after denial (generated by marketing agent)

For denied applications, the denial email already contains all the information
the customer needs (reasons, improvement steps, credit report bodies, AFCA).
The marketing agent follows up with alternative product offers. A separate
"denied follow-up" lifecycle email is redundant and was removed.

Similarly, the "under review" notification was removed — for applications that
process in minutes, an extra "we're looking at it" email adds noise, not value.

This module handles stage 1 only. Stages 2-3 are AI-generated.
"""

import logging
from datetime import datetime

from apps.email_engine.models import GeneratedEmail
from apps.email_engine.services.sender import send_decision_email

logger = logging.getLogger(__name__)


def send_application_received(application):
    """Stage 1: Acknowledge receipt of loan application.

    Sent immediately when a customer submits an application.
    Sets expectations for timeline and next steps.
    """
    applicant = application.applicant
    name = applicant.first_name or applicant.username
    purpose = application.get_purpose_display() if hasattr(application, "get_purpose_display") else application.purpose
    amount = f"${application.loan_amount:,.2f}"
    ref_code = (
        f"{application.purpose.upper()[:3]}-{datetime.now().strftime('%Y%m%d')}-{str(application.id)[:4].upper()}"
    )

    subject = f"We've Received Your {purpose.title()} Loan Application | Ref #{ref_code}"
    body = f"""Dear {name},

Thank you for your {purpose} loan application with AussieLoanAI. We have everything we need to get started.

Application summary:

  Loan Amount: {amount}
  Loan Purpose: {purpose.title()}
  Reference: {ref_code}

What happens next:

  1. We will review your application and supporting documents.
  2. If we need anything else from you, we will be in touch.
  3. You will receive an update within 1\u20132 business days.

You can check your application status at any time by logging into your account. If you have questions, you can reach me at 1300 000 000 or reply to this email.

Kind regards,
Sarah Mitchell
Senior Lending Officer
AussieLoanAI

This email confirms receipt of your application only and does not constitute an offer of credit.
Australian Financial Complaints Authority (AFCA) | www.afca.org.au | 1800 931 678
"""

    email = GeneratedEmail.objects.create(
        application=application,
        decision="pending",
        subject=subject,
        body=body,
        prompt_used="lifecycle_template:received",
        model_used="template",
        generation_time_ms=0,
        attempt_number=1,
        passed_guardrails=True,
    )

    # Send if applicant has email
    if applicant.email:
        send_decision_email(applicant.email, subject, body)

    logger.info("Sent application received email for %s", application.id)
    return email
