apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: celery-worker-io-pdb
  namespace: loan-approval
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: celery-worker-io
      app.kubernetes.io/component: worker
