# Generated by Django 5.0.14 on 2026-03-13 04:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedEmail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("decision", models.CharField(max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("prompt_used", models.TextField()),
                ("model_used", models.CharField(default="claude-sonnet-4-20250514", max_length=50)),
                ("generation_time_ms", models.IntegerField(null=True)),
                ("attempt_number", models.IntegerField(default=1)),
                ("passed_guardrails", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emails", to="loans.loanapplication"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuardrailLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("check_name", models.CharField(max_length=100)),
                ("passed", models.BooleanField()),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardrail_checks",
                        to="email_engine.generatedemail",
                    ),
                ),
            ],
        ),
    ]
