# Generated by Django 5.2.12 on 2026-03-20 06:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_engine", "0002_bias_report_marketing_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuardrailAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("week_start", models.DateField(db_index=True)),
                ("check_name", models.CharField(max_length=100)),
                ("total_runs", models.IntegerField(default=0)),
                ("pass_count", models.IntegerField(default=0)),
                ("fail_count", models.IntegerField(default=0)),
                ("pass_rate", models.FloatField(default=0.0)),
                ("retry_rate", models.FloatField(default=0.0, help_text="% of emails that needed at least 1 retry")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-week_start", "check_name"],
            },
        ),
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="e.g. approval_v2, denial_empathetic", max_length=100)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[("approval", "Approval"), ("denial", "Denial"), ("marketing", "Marketing")],
                        max_length=20,
                    ),
                ),
                ("template_text", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                ("total_uses", models.IntegerField(default=0)),
                ("guardrail_pass_rate", models.FloatField(blank=True, null=True)),
                ("avg_generation_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="estimated_cost_usd",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="output_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="generatedemail",
            name="template_fallback",
            field=models.BooleanField(
                default=False, help_text="True if generated from static template (Claude API unavailable)"
            ),
        ),
        migrations.AddIndex(
            model_name="guardraillog",
            index=models.Index(fields=["email", "-created_at"], name="guardrail_email_created"),
        ),
        migrations.AlterUniqueTogether(
            name="guardrailanalytics",
            unique_together={("week_start", "check_name")},
        ),
        migrations.AlterUniqueTogether(
            name="promptversion",
            unique_together={("name", "version")},
        ),
    ]
