# Generated by Django 5.0.14 on 2026-03-13 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('email_engine', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('steps', models.JSONField(default=list)),
                ('total_time_ms', models.IntegerField(null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiasReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bias_score', models.FloatField()),
                ('categories', models.JSONField(default=list)),
                ('analysis', models.TextField()),
                ('flagged', models.BooleanField(default=False)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_reports', to='agents.agentrun')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_reports', to='email_engine.generatedemail')),
            ],
        ),
        migrations.CreateModel(
            name='NextBestOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offers', models.JSONField(default=list)),
                ('analysis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_best_offers', to='agents.agentrun')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_best_offers', to='loans.loanapplication')),
            ],
        ),
    ]
