# Generated by Django 5.0.14 on 2026-03-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("escalated", "Escalated to Human"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
