# Generated by Django 5.0.14 on 2026-03-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0002_add_escalated_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="nextbestoffer",
            name="customer_retention_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="nextbestoffer",
            name="loyalty_factors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="nextbestoffer",
            name="personalized_message",
            field=models.TextField(blank=True),
        ),
    ]
