# Generated by Django 5.2.12 on 2026-03-17 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_add_ai_review_and_marketing_fields'),
        ('loans', '0005_add_hecs_bankruptcy_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('prompt_used', models.TextField()),
                ('model_used', models.CharField(default='claude-sonnet-4-20250514', max_length=50)),
                ('generation_time_ms', models.IntegerField(null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('passed_guardrails', models.BooleanField(default=False)),
                ('guardrail_results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_emails', to='agents.agentrun')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_emails', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
