# Generated by Django 5.2.12 on 2026-03-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_add_bias_report_audit_fields'),
        ('email_engine', '0002_bias_report_marketing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='biasreport',
            name='marketing_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_reports', to='agents.marketingemail'),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='report_type',
            field=models.CharField(choices=[('decision', 'Decision'), ('marketing', 'Marketing')], default='decision', max_length=20),
        ),
        migrations.AlterField(
            model_name='biasreport',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bias_reports', to='email_engine.generatedemail'),
        ),
    ]
