# Generated by Django 5.2.12 on 2026-03-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_bias_report_marketing_fields'),
        ('loans', '0008_loandecision_risk_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='total_input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='total_output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='estimated_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biasreport',
            name='output_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['application', '-created_at'], name='agentrun_app_created'),
        ),
    ]
