# Generated by Django 5.2.12 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentrun_total_cost_usd_agentrun_total_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='failure_category',
            field=models.CharField(
                blank=True,
                choices=[('transient', 'Transient'), ('permanent', 'Permanent'), ('config_error', 'Config Error')],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
