# Generated by Django 5.2.12 on 2026-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentrun_failure_category_agentrun_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingemail',
            name='blocked_reason',
            field=models.CharField(blank=True, default='', help_text='Why email was not sent (e.g. bias_check_failed, no_recipient)', max_length=100),
        ),
        migrations.AddField(
            model_name='marketingemail',
            name='delivery_error',
            field=models.TextField(blank=True, default='', help_text='SMTP error message if delivery failed'),
        ),
        migrations.AddField(
            model_name='marketingemail',
            name='sent',
            field=models.BooleanField(default=False, help_text='Whether the email was actually delivered via SMTP'),
        ),
        migrations.AddField(
            model_name='marketingemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
