# Generated by Django 5.2.12 on 2026-04-01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0010_add_marketing_delivery_tracking"),
        ("loans", "0018_remove_conditional_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "service",
                    models.CharField(
                        help_text="e.g. email_generation, bias_detection, nbo",
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="anthropic",
                        help_text="API provider",
                        max_length=50,
                    ),
                ),
                ("model_used", models.CharField(max_length=100)),
                (
                    "pii_categories",
                    models.JSONField(
                        default=list,
                        help_text="Categories of PII sent: ['name', 'income', 'employment', 'loan_amount', etc.]",
                    ),
                ),
                (
                    "prompt_hash",
                    models.CharField(
                        help_text="SHA-256 hash of prompt (not the prompt itself)",
                        max_length=64,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "destination_country",
                    models.CharField(
                        default="US",
                        help_text="ISO country code of API endpoint",
                        max_length=2,
                    ),
                ),
                (
                    "agent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_call_logs",
                        to="agents.agentrun",
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_call_logs",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["loan_application", "timestamp"],
                        name="apicalllog_app_ts",
                    ),
                ],
            },
        ),
    ]
