# Generated by Django 5.2.13 on 2026-04-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0011_apicalllog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketingemail",
            name="model_used",
            field=models.CharField(default="claude-sonnet-4-6", max_length=50),
        ),
    ]
