# Generated by Django 5.2.15 on 2026-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0012_update_default_to_sonnet_4_6"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicalllog",
            name="outcome",
            field=models.CharField(
                choices=[("success", "Success"), ("error", "Error")],
                default="success",
                help_text="Failed calls are logged too: a prompt sent before a timeout/5xx is still a disclosure",
                max_length=10,
            ),
        ),
    ]
