apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: loan-approval
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: aussieloanai
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: web
        app.kubernetes.io/part-of: aussieloanai
    spec:
      containers:
        - name: frontend
          image: ghcr.io/OWNER/loan-approval-ai-system/frontend:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            initialDelaySeconds: 20
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
