"""API contract tests using schemathesis.

Validates that the live API conforms to the OpenAPI schema generated by
drf-spectacular. Run against a local server with:

    pytest tests/test_api_contract.py --base-url http://localhost:8000

Or generate static tests from the schema:

    schemathesis run http://localhost:8000/api/schema/ --validate-schema

These tests catch:
- Responses that don't match declared status codes
- Response bodies that don't match declared schemas
- Missing required fields in responses
- Undocumented endpoints or parameters
"""

import os

import pytest

# Skip if schemathesis is not installed or no server URL configured
schemathesis = pytest.importorskip("schemathesis")

BASE_URL = os.environ.get("CONTRACT_TEST_BASE_URL", "http://localhost:8000")
SCHEMA_URL = f"{BASE_URL}/api/schema/"


@pytest.fixture(scope="module")
def api_schema():
    """Load the OpenAPI schema from the running server."""
    try:
        return schemathesis.from_url(SCHEMA_URL)
    except Exception:
        pytest.skip(f"Cannot reach schema at {SCHEMA_URL} — is the server running?")


# Stateful test: schemathesis automatically generates test cases from the schema
# and validates responses against declared schemas.
def _load_schema():
    if not os.environ.get("RUN_CONTRACT_TESTS"):
        return None
    loader = getattr(schemathesis, "from_url", None) or getattr(
        getattr(schemathesis, "openapi", None), "from_url", None
    )
    if loader is None:
        return None
    try:
        return loader(SCHEMA_URL, base_url=BASE_URL)
    except Exception:
        return None


schema = _load_schema()


if schema:

    @schema.parametrize()
    def test_api_contract(case):
        """Auto-generated contract test: validates response matches schema."""
        # Skip endpoints that require authentication for now
        # (they'll return 401, which should be a documented response)
        response = case.call()
        case.validate_response(response)
