apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loan-approval
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - celery/worker-ml.yaml
  - celery/worker-io.yaml
  - celery/beat.yaml
  - backend/pdb.yaml
  - celery/pdb-ml.yaml
  - celery/pdb-io.yaml
  - network-policy.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/part-of: aussieloanai
