# Generated by Django 5.0.14 on 2026-03-13 04:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=12)),
                ("credit_score", models.IntegerField()),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("loan_term_months", models.IntegerField(default=36)),
                ("debt_to_income", models.DecimalField(decimal_places=4, max_digits=5)),
                ("employment_length", models.IntegerField(help_text="Years of employment")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("home", "Home Purchase"),
                            ("auto", "Auto Loan"),
                            ("education", "Education"),
                            ("personal", "Personal"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "home_ownership",
                    models.CharField(
                        choices=[("own", "Own"), ("rent", "Rent"), ("mortgage", "Mortgage")], max_length=20
                    ),
                ),
                ("has_cosigner", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("review", "Under Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("decision", models.CharField(choices=[("approved", "Approved"), ("denied", "Denied")], max_length=20)),
                ("confidence", models.FloatField()),
                ("risk_score", models.FloatField(blank=True, null=True)),
                ("feature_importances", models.JSONField(default=dict)),
                ("model_version", models.CharField(max_length=100)),
                ("reasoning", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="decision", to="loans.loanapplication"
                    ),
                ),
            ],
        ),
    ]
