# Generated by Django 5.2.12 on 2026-03-18 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0005_add_hecs_bankruptcy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="annual_income",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="loan_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="loan_term_months",
            field=models.IntegerField(
                default=36,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)],
            ),
        ),
    ]
