# Generated by Django 5.2.12 on 2026-03-19 11:33

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loanapplication_annual_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='state',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('WA', 'Western Australia'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory')], default='NSW', help_text='Australian state/territory of the applicant', max_length=3),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='credit_score',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000000)]),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['applicant', '-created_at'], name='loan_applicant_created'),
        ),
    ]
