# Generated by Django 5.2.12 on 2026-03-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0008_loandecision_risk_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="avg_monthly_savings_rate",
            field=models.FloatField(blank=True, help_text="Average monthly savings rate", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="consumer_confidence",
            field=models.FloatField(blank=True, help_text="Westpac-MI Consumer Confidence Index", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="credit_history_months",
            field=models.IntegerField(blank=True, help_text="Length of credit history in months", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="days_in_overdraft_12m",
            field=models.IntegerField(blank=True, help_text="Days in overdraft in last 12 months", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="document_consistency_score",
            field=models.FloatField(blank=True, help_text="Document consistency 0-1", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="income_verification_gap",
            field=models.FloatField(blank=True, help_text="Declared vs verified income ratio", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="is_existing_customer",
            field=models.BooleanField(default=False, help_text="Existing bank customer"),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="num_bnpl_accounts",
            field=models.IntegerField(blank=True, help_text="Buy-now-pay-later accounts", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="num_credit_enquiries_6m",
            field=models.IntegerField(blank=True, help_text="Credit enquiries in last 6 months", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="num_defaults_5yr",
            field=models.IntegerField(blank=True, help_text="Defaults on credit file in last 5 years", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="num_dishonours_12m",
            field=models.IntegerField(blank=True, help_text="Bounced payments in last 12 months", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="property_growth_12m",
            field=models.FloatField(blank=True, help_text="12-month property growth for state", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="rba_cash_rate",
            field=models.FloatField(blank=True, help_text="RBA cash rate at application date", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="salary_credit_regularity",
            field=models.FloatField(blank=True, help_text="Salary credit regularity score 0-1", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="savings_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="Average savings balance", max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="total_open_accounts",
            field=models.IntegerField(blank=True, help_text="Total open credit accounts", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="unemployment_rate",
            field=models.FloatField(blank=True, help_text="State unemployment rate at application date", null=True),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="worst_arrears_months",
            field=models.IntegerField(blank=True, help_text="Worst arrears in last 24 months (0-3+)", null=True),
        ),
    ]
