# Generated by Django 5.2.12 on 2026-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0012_add_outcome_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="loandecision",
            name="shap_values",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
