# Generated by Django 5.2.12 on 2026-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0016_add_conditional_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
