# Generated by Django 5.2.12 on 2026-04-01 16:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0018_remove_conditional_status"),
        ("ml_engine", "0008_add_validation_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="consumer_objectives",
            field=models.TextField(blank=True, help_text="Consumer's stated objectives for this loan (NCCP Act s.12A)"),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="consumer_requirements",
            field=models.TextField(blank=True, help_text="Consumer's stated requirements and how this loan meets them"),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="financial_situation_notes",
            field=models.TextField(blank=True, help_text="Summary of inquiries into consumer's financial situation"),
        ),
        migrations.AlterField(
            model_name="loandecision",
            name="model_version",
            field=models.ForeignKey(
                blank=True,
                help_text="ML model version that produced this decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisions",
                to="ml_engine.modelversion",
            ),
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("decision", "Loan Decision"),
                            ("service", "Service Quality"),
                            ("privacy", "Privacy Concern"),
                            ("discrimination", "Discrimination"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("escalated_afca", "Escalated to AFCA"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("resolution", models.TextField(blank=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="ASIC RG 271: 21 days for credit complaints, 30 days for standard",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complainant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["complainant", "status"], name="complaint_user_status")],
            },
        ),
    ]
