# Generated by Django 5.2.13 on 2026-04-17 18:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0021_loandecision_counterfactual_results"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("review", "Under Review"),
                    ("queue_failed", "Queue Dispatch Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PipelineDispatchOutbox",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_outbox",
                        to="loans.loanapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Dispatch Outbox Entry",
                "verbose_name_plural": "Pipeline Dispatch Outbox",
                "ordering": ["created_at"],
            },
        ),
    ]
