# Generated by Django 5.2.13 on 2026-05-28 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0023_add_referral_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Why the applicant believes the decision is wrong')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under review'), ('upheld', 'Decision upheld'), ('overturned', 'Decision overturned'), ('withdrawn', 'Withdrawn by applicant')], db_index=True, default='requested', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('outcome_decision', models.CharField(blank=True, default='', max_length=20)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_reviews', to='loans.loanapplication')),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_decision_reviews', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='decisionreview_status_req')],
            },
        ),
    ]
