# Generated by Django 5.0.14 on 2026-03-16 03:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('checking_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account_tenure_years', models.IntegerField(default=0, help_text='Years as a customer')),
                ('has_credit_card', models.BooleanField(default=False)),
                ('has_mortgage', models.BooleanField(default=False)),
                ('has_auto_loan', models.BooleanField(default=False)),
                ('num_products', models.IntegerField(default=1, help_text='Total banking products held')),
                ('loyalty_tier', models.CharField(choices=[('standard', 'Standard'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='standard', max_length=20)),
                ('on_time_payment_pct', models.FloatField(default=100.0, help_text='Percentage of on-time payments')),
                ('previous_loans_repaid', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
