# Generated by Django 5.2.12 on 2026-03-18 00:12

import apps.accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_personal_details_and_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='primary_id_number',
            field=apps.accounts.fields.EncryptedCharField(blank=True, help_text='Encrypted at rest via Fernet', max_length=500),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='secondary_id_number',
            field=apps.accounts.fields.EncryptedCharField(blank=True, help_text='Encrypted at rest via Fernet', max_length=500),
        ),
    ]
