# Generated by Django 5.2.12 on 2026-03-18 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="employer_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("payg_permanent", "PAYG – Permanent"),
                    ("payg_casual", "PAYG – Casual"),
                    ("self_employed", "Self-Employed"),
                    ("contract", "Contract"),
                    ("retired", "Retired"),
                    ("unemployed", "Unemployed"),
                    ("home_duties", "Home Duties"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="estimated_property_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="gross_annual_income",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="housing_situation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("own_outright", "Own Outright"),
                    ("mortgage", "Mortgage"),
                    ("renting", "Renting"),
                    ("boarding", "Boarding"),
                    ("living_with_parents", "Living with Parents"),
                ],
                default="",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture, Forestry and Fishing"),
                    ("mining", "Mining"),
                    ("manufacturing", "Manufacturing"),
                    ("utilities", "Electricity, Gas, Water and Waste Services"),
                    ("construction", "Construction"),
                    ("wholesale_trade", "Wholesale Trade"),
                    ("retail_trade", "Retail Trade"),
                    ("accommodation_food", "Accommodation and Food Services"),
                    ("transport_postal", "Transport, Postal and Warehousing"),
                    ("information_media", "Information Media and Telecommunications"),
                    ("financial_insurance", "Financial and Insurance Services"),
                    ("property_services", "Rental, Hiring and Real Estate Services"),
                    ("professional_scientific", "Professional, Scientific and Technical Services"),
                    ("administrative", "Administrative and Support Services"),
                    ("public_admin", "Public Administration and Safety"),
                    ("education_training", "Education and Training"),
                    ("healthcare_social", "Health Care and Social Assistance"),
                    ("arts_recreation", "Arts and Recreation Services"),
                    ("other_services", "Other Services"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="investment_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="number_of_dependants",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)],
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="occupation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="other_credit_card_limits",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="other_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="other_income_source",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="other_loan_repayments_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="partner_annual_income",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[("email", "Email"), ("phone", "Phone"), ("sms", "SMS")], default="email", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="previous_employer",
            field=models.CharField(
                blank=True, default="", help_text="Required if less than 2 years in current role", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="previous_postcode",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="previous_state",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="previous_suburb",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="rent_or_board_monthly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="savings_other_institutions",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="superannuation_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="time_at_current_address_years",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="vehicle_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="years_in_current_role",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
