# Generated by Django 5.2.12 on 2026-03-20 06:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_customerprofile_employer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="data_sharing_consent",
            field=models.BooleanField(default=False, help_text="Consent to share data with third parties"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="marketing_consent",
            field=models.BooleanField(default=False, help_text="Consent to receive marketing communications"),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="privacy_consent_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="privacy_consent_given",
            field=models.BooleanField(default=False, help_text="Customer consented to Privacy Collection Notice"),
        ),
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_points", models.IntegerField(default=0, help_text="Total ID verification points (need 100)")),
                (
                    "primary_id_points",
                    models.IntegerField(default=0, help_text="Points from primary ID (e.g. passport=70)"),
                ),
                ("secondary_id_points", models.IntegerField(default=0, help_text="Points from secondary ID")),
                ("supplementary_points", models.IntegerField(default=0, help_text="Points from supplementary docs")),
                ("sanctions_checked", models.BooleanField(default=False)),
                ("sanctions_clear", models.BooleanField(default=None, null=True)),
                ("sanctions_check_date", models.DateTimeField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_verifications_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
