# Generated by Django 5.2.12 on 2026-03-26 14:07

import apps.accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_encrypt_existing_pii'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address_line_1',
            field=apps.accounts.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address_line_2',
            field=apps.accounts.fields.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='employer_name',
            field=apps.accounts.fields.EncryptedCharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=apps.accounts.fields.EncryptedCharField(blank=True, help_text='Australian mobile or landline', max_length=500),
        ),
    ]
