# Generated by Django 5.2.13 on 2026-04-18 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_encrypt_income_dob_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="on_time_payment_pct",
            field=models.FloatField(
                default=100.0,
                help_text="Percentage of on-time payments (0-100)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
