# Generated by Django 5.0.14 on 2026-03-13 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm', models.CharField(choices=[('rf', 'Random Forest'), ('xgb', 'XGBoost')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(null=True)),
                ('precision', models.FloatField(null=True)),
                ('recall', models.FloatField(null=True)),
                ('f1_score', models.FloatField(null=True)),
                ('auc_roc', models.FloatField(null=True)),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('feature_importances', models.JSONField(default=dict)),
                ('roc_curve_data', models.JSONField(default=dict)),
                ('training_params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction', models.CharField(max_length=20)),
                ('probability', models.FloatField()),
                ('feature_importances', models.JSONField(default=dict)),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='loans.loanapplication')),
                ('model_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_engine.modelversion')),
            ],
        ),
    ]
