# Generated by Django 5.2.12 on 2026-03-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="file_hash",
            field=models.CharField(blank=True, help_text="SHA-256 hash for integrity verification", max_length=64),
        ),
    ]
