# Generated by Django 5.2.12 on 2026-03-20 06:30

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0003_modelversion_brier_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="traffic_percentage",
            field=models.IntegerField(
                default=100,
                help_text="Percentage of predictions routed to this model (for A/B testing)",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.CreateModel(
            name="DriftReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("report_date", models.DateField(db_index=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("num_predictions", models.IntegerField(default=0)),
                (
                    "psi_score",
                    models.FloatField(
                        help_text="PSI: <0.1 stable, 0.1-0.25 moderate, >0.25 significant drift", null=True
                    ),
                ),
                ("psi_per_feature", models.JSONField(default=dict, help_text="PSI score per feature")),
                ("mean_probability", models.FloatField(null=True)),
                ("std_probability", models.FloatField(null=True)),
                ("approval_rate", models.FloatField(null=True)),
                ("drift_detected", models.BooleanField(default=False)),
                (
                    "alert_level",
                    models.CharField(
                        choices=[("none", "None"), ("moderate", "Moderate"), ("significant", "Significant")],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_reports",
                        to="ml_engine.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
                "unique_together": {("model_version", "report_date")},
            },
        ),
    ]
