# Generated by Django 5.2.12 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0004_modelversion_traffic_percentage_driftreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelversion",
            name="algorithm",
            field=models.CharField(
                choices=[("rf", "Random Forest"), ("xgb", "XGBoost"), ("lgbm", "LightGBM"), ("ensemble", "Ensemble")],
                max_length=20,
            ),
        ),
    ]
