# Generated by Django 5.2.12 on 2026-03-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0005_alter_modelversion_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='decision_threshold_approve',
            field=models.FloatField(blank=True, help_text='Confidence >= this threshold → approve', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='decision_threshold_deny',
            field=models.FloatField(blank=True, help_text='Confidence <= this threshold → deny', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='decision_threshold_review',
            field=models.FloatField(blank=True, help_text='Between deny and approve → human review', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='explainability_method',
            field=models.CharField(default='shap_tree', help_text='Explainability framework used (e.g. shap_tree, lime)', max_length=50),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Scheduled performance review / revalidation date', null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='retired_at',
            field=models.DateTimeField(blank=True, help_text='When this model version was retired from production', null=True),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='algorithm',
            field=models.CharField(choices=[('rf', 'Random Forest'), ('xgb', 'XGBoost')], max_length=20),
        ),
    ]
