# Generated by Django 5.2.12 on 2026-03-26 14:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0007_modelversion_retraining_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelValidationReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("validator_name", models.CharField(help_text="Name of the independent validator", max_length=255)),
                ("validator_role", models.CharField(help_text="e.g. Risk Manager, External Auditor", max_length=100)),
                ("validation_date", models.DateField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("approved", "Approved for Production"),
                            ("conditional", "Approved with Conditions"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "methodology",
                    models.TextField(
                        help_text="Description of validation methodology (holdout test, challenger comparison, etc.)"
                    ),
                ),
                ("findings", models.TextField(help_text="Key findings from the validation")),
                (
                    "conditions",
                    models.TextField(blank=True, help_text="Conditions for approval (if outcome is conditional)"),
                ),
                (
                    "challenger_comparison",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metrics comparison between champion and challenger model(s)",
                    ),
                ),
                (
                    "holdout_metrics",
                    models.JSONField(
                        blank=True, default=dict, help_text="Performance metrics on holdout/out-of-time sample"
                    ),
                ),
                (
                    "fairness_review",
                    models.JSONField(blank=True, default=dict, help_text="Fairness assessment results from validation"),
                ),
                ("signed_off", models.BooleanField(default=False)),
                ("signed_off_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_validation_due",
                    models.DateField(
                        blank=True,
                        help_text="When the next validation is required (typically annual for high-risk models)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_reports",
                        to="ml_engine.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-validation_date"],
            },
        ),
    ]
