# Generated by Django 5.2.13 on 2026-04-14 16:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ml_engine", "0008_add_validation_report"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("inputs_hash", models.CharField(db_index=True, max_length=64)),
                ("rate_min", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("rate_max", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("comparison_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                (
                    "estimated_monthly_repayment",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("eligible", models.BooleanField(default=True)),
                ("ineligible_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [models.Index(fields=["user", "-created_at"], name="ml_engine_q_user_id_3625f9_idx")],
            },
        ),
    ]
